name:  Oneblock
main:  Oneblock.Oneblock
version:  1.1.7
api-version: 1.13
author:  MrMarL
softdepend: [PlaceholderAPI , WorldGuard]
loadbefore: [Multiverse-Core]
commands:
  oneblock:
    description: Oneblock main command.
    aliases: ob
    usage: /ob join
  spawn:
    description: Spawn main command.
    aliases: sp
    usage: /spawn
  ob j:
  ob ver:
    description: Version.
permissions:
    Oneblock.set:
        description: For admin
        default: op
    Oneblock.join:
        description: For all
        default: true
    Oneblock.invite:
        default: true
    Oneblock.visit:
        default: false
    Oneblock.ignoreBarrier:
        default: op